public class ColoursNamesList {
    public static void ColoursNamesList(){
        List<String>ColoursNamesList=new List<string>();
    ColoursNamesList.add ('pink');
    ColoursNamesList.add('green');
    ColoursNamesList.add('blue');
    ColoursNamesList.add('red');
    system.debug('colours names are: '+ ColoursNamesList);
    
    
    List<string>colours2=new List<string>{'yellow','brown'};
        
        ColoursnamesList.addall(colours2);
    system.debug('after adding list:' + ColoursNamesList);
}

}